Fixing the button size for mobile.
Tech-Start-UCalgary/tsu-website pull request #282
Opened 2021-12-03 00:51 UTC by LabibAfsarAhmed

- Fix the button size so that it changes according to the mobile device.

2021-12-06 00:45 UTC, Niyousha99 commented on src/components/FeaturedProject.css
> +    box-shadow: 2px 4px #4dd6a8;
Could you replace the box-shadow hex color with the global variable `--primary-green` provided in App.css?

2021-12-06 00:47 UTC, Niyousha99 requested changes
I'm not feeling the "->" in the project button text. How about we remove it?

2022-01-22 01:40 UTC, Niyousha99 approved these changes
LGTM!

2022-01-22 22:26 UTC, ss1106 approved these changes
LGTM

2022-01-23 16:39 UTC, merged