Redesigned toggle button
Tech-Start-UCalgary/tsu-website pull request #293
Opened 2022-01-14 02:03 UTC by Sahitiakella

2022-01-22 02:13 UTC, Niyousha99 requested changes
Now that there is enough contract between the toggle button icons anch background colors, let's remove the darker borders please.

2022-01-22 02:13 UTC, Niyousha99 commented on src/pages/DocsPage.tsx
> +                <FontAwesomeIcon icon={faMoon} className="faMoon" />
It looks like the chechbox is just covering one of the icons each time. You can see the sun icon peeking out of the checkbox: 
![image](https://user-images.githubusercontent.com/59885733/150620589-e2c990da-378e-4568-ab10-c2d7a873349e.png)

Let's these icons render conditionally depending on the theme, like this:
` <FontAwesomeIcon> { theme === "light" ? icon={faMoon} className="faMoon" : icon={faSun} className="faSun" } />`

2022-01-23 18:04 UTC, Niyousha99 approved these changes
Looks great, good job!

2022-01-23 19:34 UTC, TakahiroFujitaSJB approved these changes
Looks good to me, though I have no way to check it for mobile view.

2022-01-23 21:34 UTC, merged